name: mude_core
description: Projeto Core dedicado ao mude.
version: 0.4.0+8
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  intl:
  flutter_svg: ^2.0.1
  just_audio: ^0.9.39
  just_audio_background:
  rxdart:
  audio_session:

  mude_tokens:
    path: ../mude-tokens

  mude_assets:
    path: ../mude-assets
  equatable: ^2.0.5
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.3

  network_image_mock: ^2.1.1

scripts:
  dcm: dart pub run dart_code_metrics:metrics analyze lib
  coverage: flutter test --coverage && genhtml coverage/lcov.info -o coverage/html && open coverage/html/index.html
  metrics: pub run dart_code_metrics:metrics analyze lib -r html && open metrics/index.html

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - test/assets/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
